### ISSUE TITLE
I fail to load images

### ISSUE THREAD

**Issue by ema79** [worron/aniwall#1]
Hi, was just trying "Aniwall"
the program loads just fine and seems to work fine, but I found myself  not able to browse images from local files. Only the sample is loaded by default.
From the terminal I got this Warning

```
WARNING: 2018-06-27 23:25:16,320 parser.py:load_images():L191 No image was found.
Load test sample.
```

Have I missed something?

Tnx

**Comment by worron** [comment]
You need download images from this [repo](https://github.com/worron/wallpapers). Then in application main menu Preferences -> Add images directory -> Rescan directories.

**Comment by ema79** [comment]
omg ...
I feel stupid for this ...
never saw that button before :(
anyway many tnx

**Comment by worron** [comment]
Can be closed I believe.
