### ISSUE TITLE
How to get a svg image that could be recognized by the aniwall

### ISSUE THREAD

**Issue by Dtover** [worron/aniwall#2]
hi, I've seen your awesomewm demo in youtube. It really appeals to me, and I want to change the background image. I find this app in your other video, but I can not get a svg image that could be recognized by aniwall other than the images in your another repos wallpapers, I tried to convert other format images to svg, but aniwall return errors as below. So could you tell how did you convert images to svg ?  
```
ERROR: 2020-03-18 19:57:02,993 parser.py:load_images():L187 Broken image file:
/home/dtover/Downloads/svg2/Ryuk.svg
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aniwall/parser.py", line 178, in load_images
    temp_data = self._load_image_data(None, file_)
  File "/usr/lib/python3.8/site-packages/aniwall/parser.py", line 152, in _load_image_data
    imagedata.set_transform(transform_tag)
  File "/usr/lib/python3.8/site-packages/aniwall/parser.py", line 53, in set_transform
    attribute = tag.get("transform")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by worron** [comment]
The app can recognize specially prepared svg only. Manual svg editing and adding necessary tags is the only way to make new images for `aniwall`. Check "Image Pattern Format" section in readme for more details.

**Comment by Dtover** [comment]
thank you for replying, due to my poor knowledge in image processing, I thought images just need to be converted simply then could be used. I didn't pay too much attention to that section. Then I will learn something about image processing. Thank you again for this amzing work.
